#!/usr/bin/env python3
"""
Re-generates Nyx8266/webfiles.h from web_interface/ source files.
Run from the repo root: python tools/build_webfiles.py
"""
import os, gzip, sys

ROOT   = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC    = os.path.join(ROOT, "web_interface")
DST    = os.path.join(ROOT, "Nyx8266", "webfiles.h")

# (variable_name, source_path_relative_to_web_interface)
FILES = [
    ("connectinghtml", "connecting.html"),
    ("loginhtml",      "login.html"),
    ("indexhtml",      "index.html"),
    ("scanhtml",       "scan.html"),
    ("infohtml",       "info.html"),
    ("fsmanagerhtml",  "fsmanager.html"),
    ("ssidshtml",      "ssids.html"),
    ("attackhtml",     "attack.html"),
    ("settingshtml",   "settings.html"),
    ("stylecss",       "style.css"),
    ("ssidsjs",        "js/ssids.js"),
    ("sitejs",         "js/site.js"),
    ("fsjs",           "js/fs.js"),
    ("attackjs",       "js/attack.js"),
    ("scanjs",         "js/scan.js"),
    ("settingsjs",     "js/settings.js"),
    # language files
    ("hulang",   "lang/hu.lang"),
    ("jalang",   "lang/ja.lang"),
    ("nllang",   "lang/nl.lang"),
    ("filang",   "lang/fi.lang"),
    ("cnlang",   "lang/cn.lang"),
    ("rulang",   "lang/ru.lang"),
    ("pllang",   "lang/pl.lang"),
    ("uklang",   "lang/uk.lang"),
    ("delang",   "lang/de.lang"),
    ("itlang",   "lang/it.lang"),
    ("enlang",   "lang/en.lang"),
    ("frlang",   "lang/fr.lang"),
    ("inlang",   "lang/in.lang"),
    ("kolang",   "lang/ko.lang"),
    ("rolang",   "lang/ro.lang"),
    ("dalang",   "lang/da.lang"),
    ("ptbrlang", "lang/ptbr.lang"),
    ("cslang",   "lang/cs.lang"),
    ("tlhlang",  "lang/tlh.lang"),
    ("eslang",   "lang/es.lang"),
    ("thlang",   "lang/th.lang"),
]

def to_c_array(name, data):
    hex_bytes = ", ".join("0x{:02X}".format(b) for b in data)
    return "const char {}[] PROGMEM = {{{}}};".format(name, hex_bytes)

def compress(path):
    with open(path, "rb") as f:
        raw = f.read()
    return gzip.compress(raw, compresslevel=9)

lines = [
    "// AUTO-GENERATED by tools/build_webfiles.py — do not edit by hand",
    "#ifndef webfiles_h",
    "#define webfiles_h",
    "",
    '#include "EvilTwin.h"',
    "",
    "// comment that out if you want to save program memory and know how to upload the web files to the SPIFFS manually",
    "#define USE_PROGMEM_WEB_FILES",
    "",
    "#ifdef USE_PROGMEM_WEB_FILES",
    "",
]

total_raw = 0
total_gz  = 0
missing   = []

for varname, relpath in FILES:
    fpath = os.path.join(SRC, relpath)
    if not os.path.exists(fpath):
        missing.append(relpath)
        continue
    raw = open(fpath, "rb").read()
    gz  = gzip.compress(raw, compresslevel=9)
    total_raw += len(raw)
    total_gz  += len(gz)
    lines.append(to_c_array(varname, gz))
    lines.append("")
    print(f"  {varname:20s}  {len(raw):6d} -> {len(gz):6d} bytes  ({100-int(len(gz)/len(raw)*100)}% saved)")

lines += [
    "#endif /* USE_PROGMEM_WEB_FILES */",
    "",
    "extern bool progmemToSpiffs(const char* adr, int len, String path);",
    "",
    "inline void copyWebFiles(bool force) {",
]
for varname, relpath in FILES:
    fpath = os.path.join(SRC, relpath)
    if not os.path.exists(fpath):
        continue
    webpath = "/web/" + relpath
    lines.append(f'    if(force) progmemToSpiffs({varname}, sizeof({varname}), "{webpath}");')
lines += ["}", "", "#endif /* webfiles_h */", ""]

with open(DST, "w", newline="\n") as f:
    f.write("\n".join(lines))

print(f"\nTotal: {total_raw:,} raw -> {total_gz:,} gzipped  ({100-int(total_gz/total_raw*100)}% saved)")
print(f"Written: {DST}")
if missing:
    print(f"MISSING (kept old data): {missing}")
